# gldt-DBWr8gxnMfLL6rfgDkTm


nodeLinker: node-modules
npmRegistryServer: 'https://registry.yarnpkg.com'

npmScopes:
  owlint:
    npmRegistryServer: 'https://git.fenrys.io/api/v4/projects/454/packages/npm'
    npmAlwaysAuth: true
    npmAuthToken: gldt-DBWr8gxnMfLL6rfgDkTm

npmRegistries:
  'https://git.fenrys.io/api/v4/projects/454/packages/npm':
    npmAlwaysAuth: true
    npmAuthToken: gldt-DBWr8gxnMfLL6rfgDkTm

unsafeHttpWhitelist:
  - "git.fenrys.io"