nodeLinker: node-modules

npmScopes:
  owlint:
    npmRegistryServer: "https://git.fenrys.io/api/v4/projects/454/packages/npm"
    npmAlwaysAuth: true
    npmAuthToken: "gldt-DBWr8gxnMfLL6rfgDkTm"
  awesome.me:
    npmRegistryServer: "https://npm.fontawesome.com"
    npmAlwaysAuth: true
    npmAuthToken: "E22FEC14-1410-4FD1-BAF2-61ADF3F32C55"
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com"
    npmAlwaysAuth: true
    npmAuthToken: "E22FEC14-1410-4FD1-BAF2-61ADF3F32C55"
