services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mint_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build: 
      context: ./mint-back
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mint_db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - N8N_BASE_URL=http://ec2-34-244-245-92.eu-west-1.compute.amazonaws.com:5678
      - N8N_WEBHOOK_ID=57be7c18-e8b2-47aa-b9aa-f7c2696f4523
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "8000:8000"

  # Nuxt Frontend
  frontend:
    build:
      context: ./mint-front
    restart: always
    environment:
      - NUXT_PUBLIC_BACKEND_API=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: 

  