/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<'/(home)', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/admin/(admin)': RouteRecordInfo<'/admin/(admin)', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/costs': RouteRecordInfo<'/admin/costs', '/admin/costs', Record<never, never>, Record<never, never>>,
    '/admin/workspaces': RouteRecordInfo<'/admin/workspaces', '/admin/workspaces', Record<never, never>, Record<never, never>>,
    '/admin/workspaces.[workspaceId]': RouteRecordInfo<'/admin/workspaces.[workspaceId]', '/admin/workspaces/:workspaceId', { workspaceId: ParamValue<true> }, { workspaceId: ParamValue<false> }>,
    '/admin/workspaces.create': RouteRecordInfo<'/admin/workspaces.create', '/admin/workspaces/create', Record<never, never>, Record<never, never>>,
    '/admin.workflows': RouteRecordInfo<'/admin.workflows', '/admin/workflows', Record<never, never>, Record<never, never>>,
    '/auth/callback': RouteRecordInfo<'/auth/callback', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/auth/silent-callback': RouteRecordInfo<'/auth/silent-callback', '/auth/silent-callback', Record<never, never>, Record<never, never>>,
    '/companies': RouteRecordInfo<'/companies', '/companies', Record<never, never>, Record<never, never>>,
    '/folders/(list)': RouteRecordInfo<'/folders/(list)', '/folders', Record<never, never>, Record<never, never>>,
    '/folders/[folderId]': RouteRecordInfo<'/folders/[folderId]', '/folders/:folderId', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }, '/folders/[folderId]/(folderId)' | '/folders/[folderId]/companies/[companyId]' | '/folders/[folderId]/companies/[companyId]/' | '/folders/[folderId]/companies/[companyId]/csr' | '/folders/[folderId]/companies/[companyId]/jobs' | '/folders/[folderId]/companies/[companyId]/press' | '/folders/[folderId]/companies/[companyId]/products' | '/folders/[folderId]/companies/[companyId]/profile' | '/folders/[folderId]/companies/[companyId]/team' | '/folders/[folderId]/companies/[companyId]/timeline' | '/folders/[folderId]/create/company' | '/folders/[folderId]/create/company-csv' | '/folders/[folderId]/edit'>,
    '/folders/[folderId]/(folderId)': RouteRecordInfo<'/folders/[folderId]/(folderId)', '/folders/:folderId', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]', '/folders/:folderId/companies/:companyId', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }, '/folders/[folderId]/companies/[companyId]/' | '/folders/[folderId]/companies/[companyId]/csr' | '/folders/[folderId]/companies/[companyId]/jobs' | '/folders/[folderId]/companies/[companyId]/press' | '/folders/[folderId]/companies/[companyId]/products' | '/folders/[folderId]/companies/[companyId]/profile' | '/folders/[folderId]/companies/[companyId]/team' | '/folders/[folderId]/companies/[companyId]/timeline'>,
    '/folders/[folderId]/companies/[companyId]/': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/', '/folders/:folderId/companies/:companyId', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/csr': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/csr', '/folders/:folderId/companies/:companyId/csr', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/jobs': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/jobs', '/folders/:folderId/companies/:companyId/jobs', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/press': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/press', '/folders/:folderId/companies/:companyId/press', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/products': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/products', '/folders/:folderId/companies/:companyId/products', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/profile': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/profile', '/folders/:folderId/companies/:companyId/profile', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/team': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/team', '/folders/:folderId/companies/:companyId/team', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/companies/[companyId]/timeline': RouteRecordInfo<'/folders/[folderId]/companies/[companyId]/timeline', '/folders/:folderId/companies/:companyId/timeline', { folderId: ParamValue<true>, companyId: ParamValue<true> }, { folderId: ParamValue<false>, companyId: ParamValue<false> }>,
    '/folders/[folderId]/create/company': RouteRecordInfo<'/folders/[folderId]/create/company', '/folders/:folderId/create/company', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }>,
    '/folders/[folderId]/create/company-csv': RouteRecordInfo<'/folders/[folderId]/create/company-csv', '/folders/:folderId/create/company-csv', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }>,
    '/folders/[folderId]/edit': RouteRecordInfo<'/folders/[folderId]/edit', '/folders/:folderId/edit', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }>,
    '/folders/create': RouteRecordInfo<'/folders/create', '/folders/create', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>, '/settings/appearance' | '/settings/profile' | '/settings/security'>,
    '/settings/appearance': RouteRecordInfo<'/settings/appearance', '/settings/appearance', Record<never, never>, Record<never, never>>,
    '/settings/profile': RouteRecordInfo<'/settings/profile', '/settings/profile', Record<never, never>, Record<never, never>>,
    '/settings/security': RouteRecordInfo<'/settings/security', '/settings/security', Record<never, never>, Record<never, never>>,
    '/team': RouteRecordInfo<'/team', '/team', Record<never, never>, Record<never, never>, '/team/apis' | '/team/settings' | '/team/users'>,
    '/team/apis': RouteRecordInfo<'/team/apis', '/team/apis', Record<never, never>, Record<never, never>>,
    '/team/settings': RouteRecordInfo<'/team/settings', '/team/settings', Record<never, never>, Record<never, never>>,
    '/team/users': RouteRecordInfo<'/team/users', '/team/users', Record<never, never>, Record<never, never>>,
    '/ui-demo': RouteRecordInfo<'/ui-demo', '/ui-demo', Record<never, never>, Record<never, never>>,
  }
}
