/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<'/(home)', '/', Record<never, never>, Record<never, never>>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/admin/(admin)': RouteRecordInfo<'/admin/(admin)', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/costs': RouteRecordInfo<'/admin/costs', '/admin/costs', Record<never, never>, Record<never, never>>,
    '/admin/workspaces': RouteRecordInfo<'/admin/workspaces', '/admin/workspaces', Record<never, never>, Record<never, never>>,
    '/admin/workspaces.[workspaceId]': RouteRecordInfo<'/admin/workspaces.[workspaceId]', '/admin/workspaces/:workspaceId', { workspaceId: ParamValue<true> }, { workspaceId: ParamValue<false> }>,
    '/admin/workspaces.create': RouteRecordInfo<'/admin/workspaces.create', '/admin/workspaces/create', Record<never, never>, Record<never, never>>,
    '/admin.workflows': RouteRecordInfo<'/admin.workflows', '/admin/workflows', Record<never, never>, Record<never, never>>,
    '/auth/callback': RouteRecordInfo<'/auth/callback', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/auth/silent-callback': RouteRecordInfo<'/auth/silent-callback', '/auth/silent-callback', Record<never, never>, Record<never, never>>,
    '/companies': RouteRecordInfo<'/companies', '/companies', Record<never, never>, Record<never, never>, '/companies/(list)' | '/companies/[companyId]' | '/companies/[companyId]/' | '/companies/[companyId]/jobs' | '/companies/[companyId]/press' | '/companies/[companyId]/products' | '/companies/[companyId]/profile' | '/companies/[companyId]/team' | '/companies/[companyId]/timeline'>,
    '/companies/(list)': RouteRecordInfo<'/companies/(list)', '/companies', Record<never, never>, Record<never, never>>,
    '/companies/[companyId]': RouteRecordInfo<'/companies/[companyId]', '/companies/:companyId', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }, '/companies/[companyId]/' | '/companies/[companyId]/jobs' | '/companies/[companyId]/press' | '/companies/[companyId]/products' | '/companies/[companyId]/profile' | '/companies/[companyId]/team' | '/companies/[companyId]/timeline'>,
    '/companies/[companyId]/': RouteRecordInfo<'/companies/[companyId]/', '/companies/:companyId', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/companies/[companyId]/jobs': RouteRecordInfo<'/companies/[companyId]/jobs', '/companies/:companyId/jobs', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/companies/[companyId]/press': RouteRecordInfo<'/companies/[companyId]/press', '/companies/:companyId/press', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/companies/[companyId]/products': RouteRecordInfo<'/companies/[companyId]/products', '/companies/:companyId/products', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/companies/[companyId]/profile': RouteRecordInfo<'/companies/[companyId]/profile', '/companies/:companyId/profile', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/companies/[companyId]/team': RouteRecordInfo<'/companies/[companyId]/team', '/companies/:companyId/team', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/companies/[companyId]/timeline': RouteRecordInfo<'/companies/[companyId]/timeline', '/companies/:companyId/timeline', { companyId: ParamValue<true> }, { companyId: ParamValue<false> }>,
    '/folders/(list)': RouteRecordInfo<'/folders/(list)', '/folders', Record<never, never>, Record<never, never>>,
    '/folders/[folderId]': RouteRecordInfo<'/folders/[folderId]', '/folders/:folderId', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }, '/folders/[folderId]/create/company'>,
    '/folders/[folderId]/create/company': RouteRecordInfo<'/folders/[folderId]/create/company', '/folders/:folderId/create/company', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }>,
    '/folders/[folderId].create.company': RouteRecordInfo<'/folders/[folderId].create.company', '/folders/:folderId/create/company', { folderId: ParamValue<true> }, { folderId: ParamValue<false> }>,
    '/folders/create': RouteRecordInfo<'/folders/create', '/folders/create', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>, '/settings/appearance' | '/settings/profile' | '/settings/security'>,
    '/settings/appearance': RouteRecordInfo<'/settings/appearance', '/settings/appearance', Record<never, never>, Record<never, never>>,
    '/settings/profile': RouteRecordInfo<'/settings/profile', '/settings/profile', Record<never, never>, Record<never, never>>,
    '/settings/security': RouteRecordInfo<'/settings/security', '/settings/security', Record<never, never>, Record<never, never>>,
    '/team': RouteRecordInfo<'/team', '/team', Record<never, never>, Record<never, never>>,
    '/ui-demo': RouteRecordInfo<'/ui-demo', '/ui-demo', Record<never, never>, Record<never, never>>,
  }
}
