from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.models.task import TaskStatus, TaskType


class TaskCreate(BaseModel):
    """Request payload to create a new task."""

    company_id: int = Field(..., description="ID of the company to run the task for")
    type: TaskType = Field(..., description="Type of data-collection task")

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {"company_id": 42, "type": "profile"},
            ],
        },
    )


class TaskTokenUpdate(BaseModel):
    """Token usage update sent by workflow callbacks."""

    input_tokens: int | None = Field(None, description="Number of input tokens consumed")
    output_tokens: int | None = Field(None, description="Number of output tokens generated")
    total_cost: float | None = Field(None, description="Total cost in USD")

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {"input_tokens": 1200, "output_tokens": 800, "total_cost": 0.012},
            ],
        },
    )


class TaskResponse(BaseModel):
    """Detailed task status returned by the API."""

    id: int = Field(..., description="Task ID")
    company_id: int = Field(..., description="Owning company ID")
    organization_id: str | None = Field(None, description="Organization UUID")
    type: TaskType = Field(..., description="Task type (profile, digital, press, ...)")
    status: TaskStatus = Field(..., description="Current status (pending, running, succeeded, error)")
    error: str | None = Field(None, description="Human-readable error message if the task failed")
    error_details: dict[str, Any] | None = Field(None, description="Structured error metadata for failed tasks")
    created_at: datetime = Field(..., description="Task creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")
    input_tokens: int | None = Field(None, description="Input tokens consumed by the workflow")
    output_tokens: int | None = Field(None, description="Output tokens generated by the workflow")
    total_cost: float | None = Field(None, description="Total LLM cost in USD")

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "examples": [
                {
                    "id": 101,
                    "company_id": 42,
                    "organization_id": "b3f1a2c4-5678-4d9e-a1b2-c3d4e5f67890",
                    "type": "profile",
                    "status": "succeeded",
                    "error": None,
                    "error_details": None,
                    "created_at": "2025-06-15T10:30:00Z",
                    "updated_at": "2025-06-15T10:32:00Z",
                    "input_tokens": 1200,
                    "output_tokens": 800,
                    "total_cost": 0.012,
                },
            ],
        },
    )
