#!/usr/bin/env python3
"""Auto-generate .gitlab/CODEOWNERS based on git commit history.

Analyzes git log per top-level directory to identify top contributors
and generates a CODEOWNERS file with real GitLab usernames.

Usage:
    python .gitlab/scripts/generate_codeowners.py
    python .gitlab/scripts/generate_codeowners.py --min-commits 3 --months 12
    python .gitlab/scripts/generate_codeowners.py --ignore bot@company.com former@company.com
    python .gitlab/scripts/generate_codeowners.py --dry-run
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections import Counter
from pathlib import Path

# Top-level directories to analyze for ownership
DIRECTORIES: list[dict[str, str]] = [
    {"path": "apps/front/", "label": "Frontend"},
    {"path": "apps/screen/", "label": "Screen Backend"},
    {"path": "apps/global-service/", "label": "Global Service"},
    {"path": "infra/", "label": "Infrastructure"},
    {"path": "docs/", "label": "Documentation"},
    {"path": "scripts/", "label": "Scripts & Tooling"},
    {"path": ".gitlab/", "label": "GitLab Configuration"},
]

# Map git commit email addresses to GitLab usernames.
# Update this mapping when onboarding new team members.
EMAIL_TO_GITLAB: dict[str, str] = {
    # Example entries — fill in with real mappings:
    # "alice@chapsvision.com": "@alice",
    # "bob@chapsvision.com": "@bob",
}

# Emails or GitLab usernames to exclude from CODEOWNERS.
# Useful for bots, former team members, or shared accounts.
IGNORED_USERS: set[str] = {
    "nmercier@chapsvision.com",   # Head of Engineering (primary email) - no time for code reviews
    "nicolas@owlint.fr",          # Head of Engineering (alt email)
    "amarchal@chapsvision.com",   # Left ChapsVision in 02/2026
    "cdognon@chapsvision.com",    # Not in a developer role
}

CODEOWNERS_PATH = Path(".gitlab/CODEOWNERS")

HEADER = """\
# CODEOWNERS — auto-assign reviewers per directory
# Generated by: .gitlab/scripts/generate_codeowners.py
# Used by CI job (assign-reviewers) to assign MR reviewers via GitLab API
# Will work natively if/when upgrading to GitLab Premium
#
# Syntax: path @group-or-user
# Doc: https://docs.gitlab.com/ee/user/project/codeowners/
"""


def _run_git(*args: str) -> str:
    """Run a git command and return stdout, or empty string on failure."""
    try:
        result = subprocess.run(
            ["git", *args],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as exc:
        print(f"Warning: git {' '.join(args)} failed: {exc.stderr.strip()}", file=sys.stderr)
        return ""


def _find_subtree_import(path: str) -> str | None:
    """Find the subtree merge commit for a given directory path.

    git subtree add creates a merge commit whose message contains
    'git-subtree-dir: <path>'. The second parent of that merge holds
    the full imported history.
    """
    output = _run_git("log", "--merges", "--oneline", "--all", "--grep", f"git-subtree-dir: {path.rstrip('/')}")
    if not output:
        return None
    # First line = most recent subtree merge for this path
    commit_hash = output.splitlines()[0].split()[0]
    # Return second parent (the imported branch)
    return _run_git("rev-parse", f"{commit_hash}^2") or None


def get_contributors(path: str, months: int) -> Counter[str]:
    """Get commit authors for a given path over the last N months.

    For directories imported via git subtree, the standard
    `git log -- <path>` only sees commits made *after* the import.
    This function also walks the subtree's second-parent history
    to capture the original contributors.
    """
    counter: Counter[str] = Counter()

    # 1. Standard git log on the current path (post-import commits)
    output = _run_git(
        "log",
        f"--since={months} months ago",
        "--format=%ae",
        "--",
        path,
    )
    if output:
        counter.update(line.strip() for line in output.splitlines() if line.strip())

    # 2. Check for subtree import and walk imported history
    subtree_parent = _find_subtree_import(path)
    if subtree_parent:
        output = _run_git(
            "log",
            f"--since={months} months ago",
            "--format=%ae",
            subtree_parent,
        )
        if output:
            counter.update(line.strip() for line in output.splitlines() if line.strip())

    return counter


def email_to_username(email: str) -> str:
    """Convert an email address to a GitLab username.

    Uses the EMAIL_TO_GITLAB mapping if available, otherwise
    derives a username from the email local part.
    """
    if email in EMAIL_TO_GITLAB:
        return EMAIL_TO_GITLAB[email]
    # Fallback: use the local part of the email prefixed with @
    local_part = email.split("@")[0]
    return f"@{local_part}"


def generate_codeowners(min_commits: int, months: int, ignored_users: set[str] | None = None) -> str:
    """Generate the CODEOWNERS file content."""
    ignored_users = ignored_users or set()
    lines: list[str] = [HEADER]

    for directory in DIRECTORIES:
        path = directory["path"]
        label = directory["label"]
        contributors = get_contributors(path, months)

        # Filter contributors with enough commits, excluding ignored users
        qualified = {
            email: count
            for email, count in contributors.items()
            if count >= min_commits and email not in ignored_users
        }

        if not qualified:
            lines.append(f"# {label}")
            lines.append(f"# {path:<25} (no contributors with >= {min_commits} commits)")
            lines.append("")
            continue

        # Sort by commit count descending
        sorted_contributors = sorted(qualified.items(), key=lambda x: x[1], reverse=True)
        usernames = [email_to_username(email) for email, _ in sorted_contributors]

        lines.append(f"# {label}")
        lines.append(f"{path:<25}{' '.join(usernames)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Auto-generate .gitlab/CODEOWNERS from git history"
    )
    parser.add_argument(
        "--min-commits",
        type=int,
        default=5,
        help="Minimum commits to qualify as owner (default: 5)",
    )
    parser.add_argument(
        "--months",
        type=int,
        default=6,
        help="Number of months of history to analyze (default: 6)",
    )
    parser.add_argument(
        "--ignore",
        nargs="+",
        default=[],
        metavar="EMAIL",
        help="Email addresses to exclude from CODEOWNERS (in addition to IGNORED_USERS)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated CODEOWNERS to stdout without writing",
    )
    args = parser.parse_args()

    ignored = IGNORED_USERS | set(args.ignore)
    content = generate_codeowners(min_commits=args.min_commits, months=args.months, ignored_users=ignored)

    if args.dry_run:
        print(content)
        print("--- dry-run: no file written ---", file=sys.stderr)
        return

    CODEOWNERS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CODEOWNERS_PATH.write_text(content, encoding="utf-8")
    print(f"Written {CODEOWNERS_PATH}")


if __name__ == "__main__":
    main()
