#!/bin/bash
set -e

if [[ -z "$KEYCLOAK_DB_USERNAME" || -z "$KEYCLOAK_DB_PASSWORD" || -z "$KEYCLOAK_DB_NAME" ]]; then
    echo "One of the variables KEYCLOAK_DB_USERNAME, KEYCLOAK_DB_PASSWORD, or KEYCLOAK_DB_NAME is not set."
    exit 1
fi

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
	CREATE ROLE "${KEYCLOAK_DB_USERNAME}" WITH LOGIN PASSWORD '${KEYCLOAK_DB_PASSWORD}';
	CREATE DATABASE "${KEYCLOAK_DB_NAME}" OWNER "${KEYCLOAK_DB_USERNAME}";
EOSQL
