/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<
      '/(home)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/403': RouteRecordInfo<
      '/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/(admin)': RouteRecordInfo<
      '/admin/(admin)',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/organizations/(list)': RouteRecordInfo<
      '/admin/organizations/(list)',
      '/admin/organizations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/organizations/[organizationId]': RouteRecordInfo<
      '/admin/organizations/[organizationId]',
      '/admin/organizations/:organizationId',
      { organizationId: ParamValue<true> },
      { organizationId: ParamValue<false> },
      | '/admin/organizations/[organizationId]/(organizationId)'
      | '/admin/organizations/[organizationId]/members'
      | '/admin/organizations/[organizationId]/profile'
      | '/admin/organizations/[organizationId]/sources'
      | '/admin/organizations/[organizationId]/tokens'
    >,
    '/admin/organizations/[organizationId]/(organizationId)': RouteRecordInfo<
      '/admin/organizations/[organizationId]/(organizationId)',
      '/admin/organizations/:organizationId',
      { organizationId: ParamValue<true> },
      { organizationId: ParamValue<false> },
      | never
    >,
    '/admin/organizations/[organizationId]/members': RouteRecordInfo<
      '/admin/organizations/[organizationId]/members',
      '/admin/organizations/:organizationId/members',
      { organizationId: ParamValue<true> },
      { organizationId: ParamValue<false> },
      | never
    >,
    '/admin/organizations/[organizationId]/profile': RouteRecordInfo<
      '/admin/organizations/[organizationId]/profile',
      '/admin/organizations/:organizationId/profile',
      { organizationId: ParamValue<true> },
      { organizationId: ParamValue<false> },
      | never
    >,
    '/admin/organizations/[organizationId]/sources': RouteRecordInfo<
      '/admin/organizations/[organizationId]/sources',
      '/admin/organizations/:organizationId/sources',
      { organizationId: ParamValue<true> },
      { organizationId: ParamValue<false> },
      | never
    >,
    '/admin/organizations/[organizationId]/tokens': RouteRecordInfo<
      '/admin/organizations/[organizationId]/tokens',
      '/admin/organizations/:organizationId/tokens',
      { organizationId: ParamValue<true> },
      { organizationId: ParamValue<false> },
      | never
    >,
    '/admin/tasks': RouteRecordInfo<
      '/admin/tasks',
      '/admin/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/usage': RouteRecordInfo<
      '/admin/usage',
      '/admin/usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users.import': RouteRecordInfo<
      '/admin/users.import',
      '/admin/users/import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin.workflows': RouteRecordInfo<
      '/admin.workflows',
      '/admin/workflows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/silent-callback': RouteRecordInfo<
      '/auth/silent-callback',
      '/auth/silent-callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/companies/create': RouteRecordInfo<
      '/companies/create',
      '/companies/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/folders/(list)': RouteRecordInfo<
      '/folders/(list)',
      '/folders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/folders/[folderId]': RouteRecordInfo<
      '/folders/[folderId]',
      '/folders/:folderId',
      { folderId: ParamValue<true> },
      { folderId: ParamValue<false> },
      | '/folders/[folderId]/(folderId)'
      | '/folders/[folderId]/companies/[companyId]'
      | '/folders/[folderId]/companies/[companyId]/'
      | '/folders/[folderId]/companies/[companyId]/corporate-structure'
      | '/folders/[folderId]/companies/[companyId]/csr'
      | '/folders/[folderId]/companies/[companyId]/jobs'
      | '/folders/[folderId]/companies/[companyId]/press'
      | '/folders/[folderId]/companies/[companyId]/products'
      | '/folders/[folderId]/companies/[companyId]/profile'
      | '/folders/[folderId]/companies/[companyId]/sanctions'
      | '/folders/[folderId]/companies/[companyId]/team'
      | '/folders/[folderId]/companies/[companyId]/timeline'
      | '/folders/[folderId]/create/company'
      | '/folders/[folderId]/create/company-csv'
      | '/folders/[folderId]/edit'
    >,
    '/folders/[folderId]/(folderId)': RouteRecordInfo<
      '/folders/[folderId]/(folderId)',
      '/folders/:folderId',
      { folderId: ParamValue<true> },
      { folderId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]',
      '/folders/:folderId/companies/:companyId',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | '/folders/[folderId]/companies/[companyId]/'
      | '/folders/[folderId]/companies/[companyId]/corporate-structure'
      | '/folders/[folderId]/companies/[companyId]/csr'
      | '/folders/[folderId]/companies/[companyId]/jobs'
      | '/folders/[folderId]/companies/[companyId]/press'
      | '/folders/[folderId]/companies/[companyId]/products'
      | '/folders/[folderId]/companies/[companyId]/profile'
      | '/folders/[folderId]/companies/[companyId]/sanctions'
      | '/folders/[folderId]/companies/[companyId]/team'
      | '/folders/[folderId]/companies/[companyId]/timeline'
    >,
    '/folders/[folderId]/companies/[companyId]/': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/',
      '/folders/:folderId/companies/:companyId',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/corporate-structure': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/corporate-structure',
      '/folders/:folderId/companies/:companyId/corporate-structure',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/csr': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/csr',
      '/folders/:folderId/companies/:companyId/csr',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/jobs': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/jobs',
      '/folders/:folderId/companies/:companyId/jobs',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/press': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/press',
      '/folders/:folderId/companies/:companyId/press',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/products': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/products',
      '/folders/:folderId/companies/:companyId/products',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/profile': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/profile',
      '/folders/:folderId/companies/:companyId/profile',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/sanctions': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/sanctions',
      '/folders/:folderId/companies/:companyId/sanctions',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/team': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/team',
      '/folders/:folderId/companies/:companyId/team',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/companies/[companyId]/timeline': RouteRecordInfo<
      '/folders/[folderId]/companies/[companyId]/timeline',
      '/folders/:folderId/companies/:companyId/timeline',
      { folderId: ParamValue<true>, companyId: ParamValue<true> },
      { folderId: ParamValue<false>, companyId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/create/company': RouteRecordInfo<
      '/folders/[folderId]/create/company',
      '/folders/:folderId/create/company',
      { folderId: ParamValue<true> },
      { folderId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/create/company-csv': RouteRecordInfo<
      '/folders/[folderId]/create/company-csv',
      '/folders/:folderId/create/company-csv',
      { folderId: ParamValue<true> },
      { folderId: ParamValue<false> },
      | never
    >,
    '/folders/[folderId]/edit': RouteRecordInfo<
      '/folders/[folderId]/edit',
      '/folders/:folderId/edit',
      { folderId: ParamValue<true> },
      { folderId: ParamValue<false> },
      | never
    >,
    '/folders/create': RouteRecordInfo<
      '/folders/create',
      '/folders/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help': RouteRecordInfo<
      '/help',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/ai-preferences'
      | '/settings/ai-preferences.ai-preferences-setup'
      | '/settings/appearance'
      | '/settings/credits'
      | '/settings/security'
      | '/settings/team-management'
    >,
    '/settings/ai-preferences': RouteRecordInfo<
      '/settings/ai-preferences',
      '/settings/ai-preferences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/ai-preferences.ai-preferences-setup': RouteRecordInfo<
      '/settings/ai-preferences.ai-preferences-setup',
      '/settings/ai-preferences/ai-preferences-setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/credits': RouteRecordInfo<
      '/settings/credits',
      '/settings/credits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/security': RouteRecordInfo<
      '/settings/security',
      '/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/team-management': RouteRecordInfo<
      '/settings/team-management',
      '/settings/team-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/target/(watch_files)/[id]': RouteRecordInfo<
      '/target/(watch_files)/[id]',
      '/target/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/target/(watch_files)/[id]/'
      | '/target/(watch_files)/[id]/audit'
      | '/target/(watch_files)/[id]/documents'
      | '/target/(watch_files)/[id]/radar'
      | '/target/(watch_files)/[id]/radar/graph'
      | '/target/(watch_files)/[id]/radar/timeline'
      | '/target/(watch_files)/[id]/scope'
    >,
    '/target/(watch_files)/[id]/': RouteRecordInfo<
      '/target/(watch_files)/[id]/',
      '/target/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/target/(watch_files)/[id]/audit': RouteRecordInfo<
      '/target/(watch_files)/[id]/audit',
      '/target/:id/audit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/target/(watch_files)/[id]/documents': RouteRecordInfo<
      '/target/(watch_files)/[id]/documents',
      '/target/:id/documents',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/target/(watch_files)/[id]/radar': RouteRecordInfo<
      '/target/(watch_files)/[id]/radar',
      '/target/:id/radar',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/target/(watch_files)/[id]/radar/graph'
      | '/target/(watch_files)/[id]/radar/timeline'
    >,
    '/target/(watch_files)/[id]/radar/graph': RouteRecordInfo<
      '/target/(watch_files)/[id]/radar/graph',
      '/target/:id/radar/graph',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/target/(watch_files)/[id]/radar/timeline': RouteRecordInfo<
      '/target/(watch_files)/[id]/radar/timeline',
      '/target/:id/radar/timeline',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/target/(watch_files)/[id]/scope': RouteRecordInfo<
      '/target/(watch_files)/[id]/scope',
      '/target/:id/scope',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/target/(watch_files)/new': RouteRecordInfo<
      '/target/(watch_files)/new',
      '/target/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/target/': RouteRecordInfo<
      '/target/',
      '/target',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tokens/history': RouteRecordInfo<
      '/tokens/history',
      '/tokens/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home).vue': {
      routes:
        | '/(home)'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/403.vue': {
      routes:
        | '/403'
      views:
        | never
    }
    'src/pages/admin/(admin).vue': {
      routes:
        | '/admin/(admin)'
      views:
        | never
    }
    'src/pages/admin/organizations/(list).vue': {
      routes:
        | '/admin/organizations/(list)'
      views:
        | never
    }
    'src/pages/admin/organizations/[organizationId].vue': {
      routes:
        | '/admin/organizations/[organizationId]'
        | '/admin/organizations/[organizationId]/(organizationId)'
        | '/admin/organizations/[organizationId]/members'
        | '/admin/organizations/[organizationId]/profile'
        | '/admin/organizations/[organizationId]/sources'
        | '/admin/organizations/[organizationId]/tokens'
      views:
        | 'default'
    }
    'src/pages/admin/organizations/[organizationId]/(organizationId).vue': {
      routes:
        | '/admin/organizations/[organizationId]/(organizationId)'
      views:
        | never
    }
    'src/pages/admin/organizations/[organizationId]/members.vue': {
      routes:
        | '/admin/organizations/[organizationId]/members'
      views:
        | never
    }
    'src/pages/admin/organizations/[organizationId]/profile.vue': {
      routes:
        | '/admin/organizations/[organizationId]/profile'
      views:
        | never
    }
    'src/pages/admin/organizations/[organizationId]/sources.vue': {
      routes:
        | '/admin/organizations/[organizationId]/sources'
      views:
        | never
    }
    'src/pages/admin/organizations/[organizationId]/tokens.vue': {
      routes:
        | '/admin/organizations/[organizationId]/tokens'
      views:
        | never
    }
    'src/pages/admin/tasks.vue': {
      routes:
        | '/admin/tasks'
      views:
        | never
    }
    'src/pages/admin/usage.vue': {
      routes:
        | '/admin/usage'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/admin/users.import.vue': {
      routes:
        | '/admin/users.import'
      views:
        | never
    }
    'src/pages/admin.workflows.vue': {
      routes:
        | '/admin.workflows'
      views:
        | never
    }
    'src/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
    }
    'src/pages/auth/silent-callback.vue': {
      routes:
        | '/auth/silent-callback'
      views:
        | never
    }
    'src/pages/companies/create.vue': {
      routes:
        | '/companies/create'
      views:
        | never
    }
    'src/pages/folders/(list).vue': {
      routes:
        | '/folders/(list)'
      views:
        | never
    }
    'src/pages/folders/[folderId].vue': {
      routes:
        | '/folders/[folderId]'
        | '/folders/[folderId]/(folderId)'
        | '/folders/[folderId]/companies/[companyId]'
        | '/folders/[folderId]/companies/[companyId]/'
        | '/folders/[folderId]/companies/[companyId]/corporate-structure'
        | '/folders/[folderId]/companies/[companyId]/csr'
        | '/folders/[folderId]/companies/[companyId]/jobs'
        | '/folders/[folderId]/companies/[companyId]/press'
        | '/folders/[folderId]/companies/[companyId]/products'
        | '/folders/[folderId]/companies/[companyId]/profile'
        | '/folders/[folderId]/companies/[companyId]/sanctions'
        | '/folders/[folderId]/companies/[companyId]/team'
        | '/folders/[folderId]/companies/[companyId]/timeline'
        | '/folders/[folderId]/create/company'
        | '/folders/[folderId]/create/company-csv'
        | '/folders/[folderId]/edit'
      views:
        | 'default'
    }
    'src/pages/folders/[folderId]/(folderId).vue': {
      routes:
        | '/folders/[folderId]/(folderId)'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId].vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]'
        | '/folders/[folderId]/companies/[companyId]/'
        | '/folders/[folderId]/companies/[companyId]/corporate-structure'
        | '/folders/[folderId]/companies/[companyId]/csr'
        | '/folders/[folderId]/companies/[companyId]/jobs'
        | '/folders/[folderId]/companies/[companyId]/press'
        | '/folders/[folderId]/companies/[companyId]/products'
        | '/folders/[folderId]/companies/[companyId]/profile'
        | '/folders/[folderId]/companies/[companyId]/sanctions'
        | '/folders/[folderId]/companies/[companyId]/team'
        | '/folders/[folderId]/companies/[companyId]/timeline'
      views:
        | 'default'
    }
    'src/pages/folders/[folderId]/companies/[companyId]/index.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/corporate-structure.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/corporate-structure'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/csr.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/csr'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/jobs.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/jobs'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/press.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/press'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/products.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/products'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/profile.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/profile'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/sanctions.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/sanctions'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/team.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/team'
      views:
        | never
    }
    'src/pages/folders/[folderId]/companies/[companyId]/timeline.vue': {
      routes:
        | '/folders/[folderId]/companies/[companyId]/timeline'
      views:
        | never
    }
    'src/pages/folders/[folderId]/create/company.vue': {
      routes:
        | '/folders/[folderId]/create/company'
      views:
        | never
    }
    'src/pages/folders/[folderId]/create/company-csv.vue': {
      routes:
        | '/folders/[folderId]/create/company-csv'
      views:
        | never
    }
    'src/pages/folders/[folderId]/edit.vue': {
      routes:
        | '/folders/[folderId]/edit'
      views:
        | never
    }
    'src/pages/folders/create.vue': {
      routes:
        | '/folders/create'
      views:
        | never
    }
    'src/pages/help.vue': {
      routes:
        | '/help'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/ai-preferences'
        | '/settings/ai-preferences.ai-preferences-setup'
        | '/settings/appearance'
        | '/settings/credits'
        | '/settings/security'
        | '/settings/team-management'
      views:
        | 'default'
    }
    'src/pages/settings/ai-preferences.vue': {
      routes:
        | '/settings/ai-preferences'
      views:
        | never
    }
    'src/pages/settings/ai-preferences.ai-preferences-setup.vue': {
      routes:
        | '/settings/ai-preferences.ai-preferences-setup'
      views:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
    }
    'src/pages/settings/credits.vue': {
      routes:
        | '/settings/credits'
      views:
        | never
    }
    'src/pages/settings/security.vue': {
      routes:
        | '/settings/security'
      views:
        | never
    }
    'src/pages/settings/team-management.vue': {
      routes:
        | '/settings/team-management'
      views:
        | never
    }
    'src/pages/target/(watch_files)/[id].vue': {
      routes:
        | '/target/(watch_files)/[id]'
        | '/target/(watch_files)/[id]/'
        | '/target/(watch_files)/[id]/audit'
        | '/target/(watch_files)/[id]/documents'
        | '/target/(watch_files)/[id]/radar'
        | '/target/(watch_files)/[id]/radar/graph'
        | '/target/(watch_files)/[id]/radar/timeline'
        | '/target/(watch_files)/[id]/scope'
      views:
        | 'default'
    }
    'src/pages/target/(watch_files)/[id]/index.vue': {
      routes:
        | '/target/(watch_files)/[id]/'
      views:
        | never
    }
    'src/pages/target/(watch_files)/[id]/audit.vue': {
      routes:
        | '/target/(watch_files)/[id]/audit'
      views:
        | never
    }
    'src/pages/target/(watch_files)/[id]/documents.vue': {
      routes:
        | '/target/(watch_files)/[id]/documents'
      views:
        | never
    }
    'src/pages/target/(watch_files)/[id]/radar.vue': {
      routes:
        | '/target/(watch_files)/[id]/radar'
        | '/target/(watch_files)/[id]/radar/graph'
        | '/target/(watch_files)/[id]/radar/timeline'
      views:
        | 'default'
    }
    'src/pages/target/(watch_files)/[id]/radar/graph.vue': {
      routes:
        | '/target/(watch_files)/[id]/radar/graph'
      views:
        | never
    }
    'src/pages/target/(watch_files)/[id]/radar/timeline.vue': {
      routes:
        | '/target/(watch_files)/[id]/radar/timeline'
      views:
        | never
    }
    'src/pages/target/(watch_files)/[id]/scope.vue': {
      routes:
        | '/target/(watch_files)/[id]/scope'
      views:
        | never
    }
    'src/pages/target/(watch_files)/new.vue': {
      routes:
        | '/target/(watch_files)/new'
      views:
        | never
    }
    'src/pages/target/index.vue': {
      routes:
        | '/target/'
      views:
        | never
    }
    'src/pages/tokens/history.vue': {
      routes:
        | '/tokens/history'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
