# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'

  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_hosts: '%env(TRUSTED_HOSTS)%'
  # See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers
  trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']

  default_locale: en
  enabled_locales: ['en', 'fr']
  set_locale_from_accept_language: true
  set_content_language_from_locale: true

  esi: false
  fragments: false

when@test:
  framework:
    test: true

when@staging:
  framework:
    test: true
