"""Add user workspace permissions table

Revision ID: cf738e5e7d13
Revises: 4af8b7ae794b
Create Date: 2025-08-06 08:44:16.375298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf738e5e7d13'
down_revision = '4af8b7ae794b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 